=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.3.9.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'date'
require 'time'

module OpenapiClient
  class AttachmentTypeEnum
    APPLICATION_PDF = "APPLICATION_PDF".freeze
    IMAGE_JPEG = "IMAGE_JPEG".freeze
    IMAGE_PNG = "IMAGE_PNG".freeze
    IMAGE_TIFF = "IMAGE_TIFF".freeze
    TEXT_PLAIN = "TEXT_PLAIN".freeze

    def self.all_vars
      @all_vars ||= [APPLICATION_PDF, IMAGE_JPEG, IMAGE_PNG, IMAGE_TIFF, TEXT_PLAIN].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AttachmentTypeEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AttachmentTypeEnum"
    end
  end
end
