=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.3.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class CanadianJurisdictionEnum
    AB = "AB".freeze
    BC = "BC".freeze
    MB = "MB".freeze
    NB = "NB".freeze
    NL = "NL".freeze
    NS = "NS".freeze
    NT = "NT".freeze
    NU = "NU".freeze
    ON = "ON".freeze
    PE = "PE".freeze
    QC = "QC".freeze
    SK = "SK".freeze
    YT = "YT".freeze

    def self.all_vars
      @all_vars ||= [AB, BC, MB, NB, NL, NS, NT, NU, ON, PE, QC, SK, YT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CanadianJurisdictionEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CanadianJurisdictionEnum"
    end
  end
end
