=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.3.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PmsRetrievalAvailableResponse < BaseBundle
    attr_accessor :message_key

    attr_accessor :original_message_identifier

    attr_accessor :source

    attr_accessor :destination

    attr_accessor :patient

    attr_accessor :practitioner

    attr_accessor :medications

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'message_key' => :'messageKey',
        :'original_message_identifier' => :'originalMessageIdentifier',
        :'source' => :'source',
        :'destination' => :'destination',
        :'patient' => :'patient',
        :'practitioner' => :'practitioner',
        :'medications' => :'medications'
      }
    end

    # Returns all the JSON keys this model knows about, including the ones defined in its parent(s)
    def self.acceptable_attributes
      attribute_map.values.concat(superclass.acceptable_attributes)
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'message_key' => :'String',
        :'original_message_identifier' => :'String',
        :'source' => :'Organization',
        :'destination' => :'Organization',
        :'patient' => :'PatientBasicInfo',
        :'practitioner' => :'PractitionerBasicInfo',
        :'medications' => :'Array<MedicationOrderInfo>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'BaseBundle'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PmsRetrievalAvailableResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PmsRetrievalAvailableResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      # call parent's initialize
      super(attributes)

      if attributes.key?(:'message_key')
        self.message_key = attributes[:'message_key']
      else
        self.message_key = nil
      end

      if attributes.key?(:'original_message_identifier')
        self.original_message_identifier = attributes[:'original_message_identifier']
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      else
        self.source = nil
      end

      if attributes.key?(:'destination')
        self.destination = attributes[:'destination']
      else
        self.destination = nil
      end

      if attributes.key?(:'patient')
        self.patient = attributes[:'patient']
      else
        self.patient = nil
      end

      if attributes.key?(:'practitioner')
        self.practitioner = attributes[:'practitioner']
      else
        self.practitioner = nil
      end

      if attributes.key?(:'medications')
        if (value = attributes[:'medications']).is_a?(Array)
          self.medications = value
        end
      else
        self.medications = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = super
      if @message_key.nil?
        invalid_properties.push('invalid value for "message_key", message_key cannot be nil.')
      end

      if @source.nil?
        invalid_properties.push('invalid value for "source", source cannot be nil.')
      end

      if @destination.nil?
        invalid_properties.push('invalid value for "destination", destination cannot be nil.')
      end

      if @patient.nil?
        invalid_properties.push('invalid value for "patient", patient cannot be nil.')
      end

      if @practitioner.nil?
        invalid_properties.push('invalid value for "practitioner", practitioner cannot be nil.')
      end

      if @medications.nil?
        invalid_properties.push('invalid value for "medications", medications cannot be nil.')
      end

      if @medications.length > 50
        invalid_properties.push('invalid value for "medications", number of items must be less than or equal to 50.')
      end

      if @medications.length < 1
        invalid_properties.push('invalid value for "medications", number of items must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @message_key.nil?
      return false if @source.nil?
      return false if @destination.nil?
      return false if @patient.nil?
      return false if @practitioner.nil?
      return false if @medications.nil?
      return false if @medications.length > 50
      return false if @medications.length < 1
      true && super
    end

    # Custom attribute writer method with validation
    # @param [Object] medications Value to be assigned
    def medications=(medications)
      if medications.nil?
        fail ArgumentError, 'medications cannot be nil'
      end

      if medications.length > 50
        fail ArgumentError, 'invalid value for "medications", number of items must be less than or equal to 50.'
      end

      if medications.length < 1
        fail ArgumentError, 'invalid value for "medications", number of items must be greater than or equal to 1.'
      end

      @medications = medications
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          message_key == o.message_key &&
          original_message_identifier == o.original_message_identifier &&
          source == o.source &&
          destination == o.destination &&
          patient == o.patient &&
          practitioner == o.practitioner &&
          medications == o.medications && super(o)
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [message_key, original_message_identifier, source, destination, patient, practitioner, medications].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      super(attributes)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = super
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
