=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.3.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PrescriptionTaskTypeEnum
    E110_M = "E110_M".freeze
    E120_M = "E120_M".freeze
    E140_M = "E140_M".freeze
    E150_M = "E150_M".freeze
    E161_M = "E161_M".freeze
    E162_M = "E162_M".freeze
    E163_M = "E163_M".freeze
    E164_M = "E164_M".freeze
    P141_M = "P141_M".freeze
    P142_M = "P142_M".freeze
    P143_M = "P143_M".freeze
    P160_M = "P160_M".freeze
    P166_M = "P166_M".freeze
    P170_M = "P170_M".freeze
    P190_M = "P190_M".freeze
    P200_M = "P200_M".freeze
    P210_M = "P210_M".freeze

    def self.all_vars
      @all_vars ||= [E110_M, E120_M, E140_M, E150_M, E161_M, E162_M, E163_M, E164_M, P141_M, P142_M, P143_M, P160_M, P166_M, P170_M, P190_M, P200_M, P210_M].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PrescriptionTaskTypeEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PrescriptionTaskTypeEnum"
    end
  end
end
