=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PrescriptionRouteOfAdministrationEnum
    BUC = "BUC".freeze
    DEN = "DEN".freeze
    EPI = "EPI".freeze
    IM = "IM".freeze
    IPINHL = "IPINHL".freeze
    IV = "IV".freeze
    NASAL = "NASAL".freeze
    NASOGASINSTIL = "NASOGASINSTIL".freeze
    OPTHALTA = "OPTHALTA".freeze
    OT = "OT".freeze
    PO = "PO".freeze
    PR = "PR".freeze
    SL = "SL".freeze
    SQ = "SQ".freeze
    TOPICAL = "TOPICAL".freeze
    TRNSDERM = "TRNSDERM".freeze
    TRNSLING = "TRNSLING".freeze
    VAGINS = "VAGINS".freeze

    def self.all_vars
      @all_vars ||= [BUC, DEN, EPI, IM, IPINHL, IV, NASAL, NASOGASINSTIL, OPTHALTA, OT, PO, PR, SL, SQ, TOPICAL, TRNSDERM, TRNSLING, VAGINS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PrescriptionRouteOfAdministrationEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PrescriptionRouteOfAdministrationEnum"
    end
  end
end
