=begin
#PrescribeIT SDK REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 5.0.27

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.53
=end

require 'date'

module PrescribeItClient
  class DetectedIssueCategoryEnum
    ALLDONE = 'ALLDONE'.freeze
    ALRTENDLATE = 'ALRTENDLATE'.freeze
    ALRTSTRTLATE = 'ALRTSTRTLATE'.freeze
    DACT = 'DACT'.freeze
    DRG = 'DRG'.freeze
    ENDLATE = 'ENDLATE'.freeze
    FOOD = 'FOOD'.freeze
    FULFIL = 'FULFIL'.freeze
    HELD = 'HELD'.freeze
    HISTORIC = 'HISTORIC'.freeze
    INTERVAL = 'INTERVAL'.freeze
    MINFREQ = 'MINFREQ'.freeze
    NHP = 'NHP'.freeze
    NONRX = 'NONRX'.freeze
    NOTACTN = 'NOTACTN'.freeze
    NOTEQUIV = 'NOTEQUIV'.freeze
    NOTEQUIVGEN = 'NOTEQUIVGEN'.freeze
    NOTEQUIVTHER = 'NOTEQUIVTHER'.freeze
    PATPREF = 'PATPREF'.freeze
    PATPREFALT = 'PATPREFALT'.freeze
    PREVINEF = 'PREVINEF'.freeze
    STRTLATE = 'STRTLATE'.freeze
    TIME = 'TIME'.freeze
    TIMING = 'TIMING'.freeze
    TOOLATE = 'TOOLATE'.freeze
    TOOSOON = 'TOOSOON'.freeze
    TPROD = 'TPROD'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = DetectedIssueCategoryEnum.constants.select { |c| DetectedIssueCategoryEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #DetectedIssueCategoryEnum" if constantValues.empty?
      value
    end
  end
end
