=begin
#PrescribeIT SDK REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 5.0.27

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.53
=end

require 'date'

module PrescribeItClient
  class IssueTypeEnum
    BUSINESS_RULE = 'BUSINESS_RULE'.freeze
    CODE_INVALID = 'CODE_INVALID'.freeze
    CONFLICT = 'CONFLICT'.freeze
    DUPLICATE = 'DUPLICATE'.freeze
    EXCEPTION = 'EXCEPTION'.freeze
    EXPIRED = 'EXPIRED'.freeze
    EXTENSION = 'EXTENSION'.freeze
    FORBIDDEN = 'FORBIDDEN'.freeze
    INCOMPLETE = 'INCOMPLETE'.freeze
    INFORMATIONAL = 'INFORMATIONAL'.freeze
    INVALID = 'INVALID'.freeze
    INVARIANT = 'INVARIANT'.freeze
    LOCK_ERROR = 'LOCK_ERROR'.freeze
    LOGIN = 'LOGIN'.freeze
    NO_STORE = 'NO_STORE'.freeze
    NOT_FOUND = 'NOT_FOUND'.freeze
    NOT_SUPPORTED = 'NOT_SUPPORTED'.freeze
    PROCESSING = 'PROCESSING'.freeze
    REQUIRED = 'REQUIRED'.freeze
    SECURITY = 'SECURITY'.freeze
    STRUCTURE = 'STRUCTURE'.freeze
    SUPPRESSED = 'SUPPRESSED'.freeze
    THROTTLED = 'THROTTLED'.freeze
    TIMEOUT = 'TIMEOUT'.freeze
    TOO_COSTLY = 'TOO_COSTLY'.freeze
    TOO_LONG = 'TOO_LONG'.freeze
    TRANSIENT = 'TRANSIENT'.freeze
    UNKNOWN = 'UNKNOWN'.freeze
    VALUE = 'VALUE'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = IssueTypeEnum.constants.select { |c| IssueTypeEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #IssueTypeEnum" if constantValues.empty?
      value
    end
  end
end
