=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'date'
require 'time'

module PrescribeItClient
  class PmsRxDispenseMedicationOrder
    attr_accessor :id

    attr_accessor :reason_codes

    attr_accessor :date_written

    attr_accessor :dispense_request

    attr_accessor :category

    attr_accessor :date_last_dispense

    attr_accessor :pharmacy_instructions

    attr_accessor :days_since_last_dispense

    attr_accessor :rendered_dosage_instruction

    attr_accessor :medication_info

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'reason_codes' => :'reasonCodes',
        :'date_written' => :'dateWritten',
        :'dispense_request' => :'dispenseRequest',
        :'category' => :'category',
        :'date_last_dispense' => :'dateLastDispense',
        :'pharmacy_instructions' => :'pharmacyInstructions',
        :'days_since_last_dispense' => :'daysSinceLastDispense',
        :'rendered_dosage_instruction' => :'renderedDosageInstruction',
        :'medication_info' => :'medicationInfo'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Identifier',
        :'reason_codes' => :'Array<PrescriptionIndicationForUseHolder>',
        :'date_written' => :'DateTimeWithPrecision',
        :'dispense_request' => :'PmsRxDispenseMedicationOrderDispenseRequestPmsRx',
        :'category' => :'PrescriptionTypeHolder',
        :'date_last_dispense' => :'DateWithPrecision',
        :'pharmacy_instructions' => :'String',
        :'days_since_last_dispense' => :'Float',
        :'rendered_dosage_instruction' => :'String',
        :'medication_info' => :'MedicationInfo'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'days_since_last_dispense',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PrescribeItClient::PmsRxDispenseMedicationOrder` initialize method"
      end

      attributes = attributes.each_with_object({}) { |(k, v), h|
        symbolized_key = k.to_sym
        unless acceptable_attributes.include?(symbolized_key)
          fail ArgumentError, "`#{k}` is not a valid attribute in `PrescribeItClient::PmsRxDispenseMedicationOrder`. Please check the name to make sure it's valid. List of attributes: " + combined_attributes.keys.inspect
        end
        h[symbolized_key] = v
      }


      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'reason_codes')
        if (value = attributes[:'reason_codes']).is_a?(Array)
          self.reason_codes = value
        end
      end

      if attributes.key?(:'date_written')
        self.date_written = attributes[:'date_written']
      else
        self.date_written = nil
      end

      if attributes.key?(:'dispense_request')
        self.dispense_request = attributes[:'dispense_request']
      else
        self.dispense_request = nil
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'date_last_dispense')
        self.date_last_dispense = attributes[:'date_last_dispense']
      end

      if attributes.key?(:'pharmacy_instructions')
        self.pharmacy_instructions = attributes[:'pharmacy_instructions']
      end

      if attributes.key?(:'days_since_last_dispense')
        self.days_since_last_dispense = attributes[:'days_since_last_dispense']
      end

      if attributes.key?(:'rendered_dosage_instruction')
        self.rendered_dosage_instruction = attributes[:'rendered_dosage_instruction']
      else
        self.rendered_dosage_instruction = nil
      end

      if attributes.key?(:'medication_info')
        self.medication_info = attributes[:'medication_info']
      else
        self.medication_info = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @date_written.nil?
        invalid_properties.push('invalid value for "date_written", date_written cannot be nil.')
      end

      if @dispense_request.nil?
        invalid_properties.push('invalid value for "dispense_request", dispense_request cannot be nil.')
      end

      if @rendered_dosage_instruction.nil?
        invalid_properties.push('invalid value for "rendered_dosage_instruction", rendered_dosage_instruction cannot be nil.')
      end

      if @medication_info.nil?
        invalid_properties.push('invalid value for "medication_info", medication_info cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @date_written.nil?
      return false if @dispense_request.nil?
      return false if @rendered_dosage_instruction.nil?
      return false if @medication_info.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          reason_codes == o.reason_codes &&
          date_written == o.date_written &&
          dispense_request == o.dispense_request &&
          category == o.category &&
          date_last_dispense == o.date_last_dispense &&
          pharmacy_instructions == o.pharmacy_instructions &&
          days_since_last_dispense == o.days_since_last_dispense &&
          rendered_dosage_instruction == o.rendered_dosage_instruction &&
          medication_info == o.medication_info
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, reason_codes, date_written, dispense_request, category, date_last_dispense, pharmacy_instructions, days_since_last_dispense, rendered_dosage_instruction, medication_info].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PrescribeItClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
