=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'date'
require 'time'

module PrescribeItClient
  class PrescriptionCancelRejectReasonEnum
    FILLED = "FILLED".freeze
    TRANSFERRED = "TRANSFERRED".freeze

    def self.all_vars
      @all_vars ||= [FILLED, TRANSFERRED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PrescriptionCancelRejectReasonEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PrescriptionCancelRejectReasonEnum"
    end
  end
end
