=begin
#PrescribeIT SDK REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 5.0.27

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.53
=end

require 'date'

module PrescribeItClient
  class PrescriptionRouteOfAdministrationEnum
    BUC = 'BUC'.freeze
    DEN = 'DEN'.freeze
    EPI = 'EPI'.freeze
    IM = 'IM'.freeze
    IPINHL = 'IPINHL'.freeze
    IV = 'IV'.freeze
    NASAL = 'NASAL'.freeze
    NASOGASINSTIL = 'NASOGASINSTIL'.freeze
    OPTHALTA = 'OPTHALTA'.freeze
    OT = 'OT'.freeze
    PO = 'PO'.freeze
    PR = 'PR'.freeze
    SL = 'SL'.freeze
    SQ = 'SQ'.freeze
    TOPICAL = 'TOPICAL'.freeze
    TRNSDERM = 'TRNSDERM'.freeze
    TRNSLING = 'TRNSLING'.freeze
    VAGINS = 'VAGINS'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PrescriptionRouteOfAdministrationEnum.constants.select { |c| PrescriptionRouteOfAdministrationEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PrescriptionRouteOfAdministrationEnum" if constantValues.empty?
      value
    end
  end
end
