=begin
#PrescribeIT SDK REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 5.0.27

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.53
=end

require 'date'

module PrescribeItClient
  class SharedPractitionerRoleEnum
    CHIROPODIST = 'CHIROPODIST'.freeze
    CHIROPRACTOR = 'CHIROPRACTOR'.freeze
    DENTALHYGIENIST = 'DENTALHYGIENIST'.freeze
    DENTIST = 'DENTIST'.freeze
    DIETICIAN = 'DIETICIAN'.freeze
    DOCTOR = 'DOCTOR'.freeze
    MIDWIFE = 'MIDWIFE'.freeze
    NURSE = 'NURSE'.freeze
    NURSEPRACTITIONER = 'NURSEPRACTITIONER'.freeze
    OPTOMETRIST = 'OPTOMETRIST'.freeze
    PHARMACIST = 'PHARMACIST'.freeze
    PODIATRIST = 'PODIATRIST'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = SharedPractitionerRoleEnum.constants.select { |c| SharedPractitionerRoleEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #SharedPractitionerRoleEnum" if constantValues.empty?
      value
    end
  end
end
