=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for emr_acknowledge_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [TransportResponse]
  describe 'emr_acknowledge_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_attachment_upload_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id 
  # @option opts [String] :content_type 
  # @option opts [File] :file 
  # @return [TransportResponse]
  describe 'emr_attachment_upload_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_formulary_request_post
  # @param [Hash] opts the optional parameters
  # @option opts [FormularyRequestParameters] :formulary_request_parameters 
  # @return [TransportResponse]
  describe 'emr_formulary_request_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_poll_inbox_get
  # @param [Hash] opts the optional parameters
  # @return [TransportResponse]
  describe 'emr_poll_inbox_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_registry_search_organization_bulk_by_fax_post
  # @param [Hash] opts the optional parameters
  # @option opts [PharmacyBulkSearchByFaxParameters] :pharmacy_bulk_search_by_fax_parameters 
  # @return [TransportResponse]
  describe 'emr_registry_search_organization_bulk_by_fax_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_registry_search_organization_bulk_by_ids_post
  # @param [Hash] opts the optional parameters
  # @option opts [PharmacyBulkSearchByIdParameters] :pharmacy_bulk_search_by_id_parameters 
  # @return [TransportResponse]
  describe 'emr_registry_search_organization_bulk_by_ids_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_registry_search_organization_by_id_post
  # @param [Hash] opts the optional parameters
  # @option opts [EmrRegistrySearchOrganizationByIdQueryParameters] :emr_registry_search_organization_by_id_query_parameters 
  # @return [TransportResponse]
  describe 'emr_registry_search_organization_by_id_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_registry_search_organization_discrete_post
  # @param [Hash] opts the optional parameters
  # @option opts [EmrRegistrySearchOrganizationDiscreteQueryParameters] :emr_registry_search_organization_discrete_query_parameters 
  # @return [TransportResponse]
  describe 'emr_registry_search_organization_discrete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_registry_search_organization_elastic_post
  # @param [Hash] opts the optional parameters
  # @option opts [EmrRegistrySearchOrganizationElasticQueryParameters] :emr_registry_search_organization_elastic_query_parameters 
  # @return [TransportResponse]
  describe 'emr_registry_search_organization_elastic_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_registry_search_practitioner_by_id_post
  # @param [Hash] opts the optional parameters
  # @option opts [EmrRegistrySearchPractitionerByIdQueryParameters] :emr_registry_search_practitioner_by_id_query_parameters 
  # @return [TransportResponse]
  describe 'emr_registry_search_practitioner_by_id_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_registry_search_practitioner_discrete_post
  # @param [Hash] opts the optional parameters
  # @option opts [EmrRegistrySearchPractitionerDiscreteQueryParameters] :emr_registry_search_practitioner_discrete_query_parameters 
  # @return [TransportResponse]
  describe 'emr_registry_search_practitioner_discrete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_registry_search_practitioner_elastic_post
  # @param [Hash] opts the optional parameters
  # @option opts [EmrRegistrySearchPractitionerElasticQueryParameters] :emr_registry_search_practitioner_elastic_query_parameters 
  # @return [TransportResponse]
  describe 'emr_registry_search_practitioner_elastic_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_request_otp_post
  # @param [Hash] opts the optional parameters
  # @option opts [RequestOtpParameters] :request_otp_parameters 
  # @return [TransportResponse]
  describe 'emr_request_otp_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_request_saml_token_post
  # @param [Hash] opts the optional parameters
  # @option opts [RequestSamlTokenParameters] :request_saml_token_parameters 
  # @return [TransportResponse]
  describe 'emr_request_saml_token_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_request_saml_token_with_ext_token_post
  # @param [Hash] opts the optional parameters
  # @option opts [RequestSamlTokenWithExternalTokenParameters] :request_saml_token_with_external_token_parameters 
  # @return [TransportResponse]
  describe 'emr_request_saml_token_with_ext_token_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_submit_to_inbox_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [TransportResponse]
  describe 'emr_submit_to_inbox_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_from_xml_formulary_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [Formulary]
  describe 'emr_transform_from_xml_formulary_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_from_xml_notification_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [NotificationMessageIssue]
  describe 'emr_transform_from_xml_notification_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_from_xml_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [InboxMessageResponse]
  describe 'emr_transform_from_xml_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_from_xml_search_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [ProviderRegistrySearchResponse]
  describe 'emr_transform_from_xml_search_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_to_xml_acknowledgment_post
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :request_body 
  # @return [String]
  describe 'emr_transform_to_xml_acknowledgment_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_to_xml_clinician_communication_post
  # @param [Hash] opts the optional parameters
  # @option opts [ClinicianCommunication] :clinician_communication 
  # @return [String]
  describe 'emr_transform_to_xml_clinician_communication_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_to_xml_emr_cancel_request_post
  # @param [Hash] opts the optional parameters
  # @option opts [EmrCancelRequest] :emr_cancel_request 
  # @return [String]
  describe 'emr_transform_to_xml_emr_cancel_request_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_to_xml_emr_deferred_request_post
  # @param [Hash] opts the optional parameters
  # @option opts [EmrDeferredRequest] :emr_deferred_request 
  # @return [String]
  describe 'emr_transform_to_xml_emr_deferred_request_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_to_xml_emr_request_post
  # @param [Hash] opts the optional parameters
  # @option opts [EmrRequest] :emr_request 
  # @return [String]
  describe 'emr_transform_to_xml_emr_request_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emr_transform_to_xml_notification_message_post
  # @param [Hash] opts the optional parameters
  # @option opts [NotificationMessage] :notification_message 
  # @return [String]
  describe 'emr_transform_to_xml_notification_message_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_acknowledge_deferred_post
  # @param [Hash] opts the optional parameters
  # @option opts [AcknowledgeDeferredParameters] :acknowledge_deferred_parameters 
  # @return [TransportResponse]
  describe 'pms_acknowledge_deferred_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_acknowledge_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [TransportResponse]
  describe 'pms_acknowledge_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_attachment_upload_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id 
  # @option opts [String] :content_type 
  # @option opts [File] :file 
  # @return [TransportResponse]
  describe 'pms_attachment_upload_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_poll_inbox_get
  # @param [Hash] opts the optional parameters
  # @return [TransportResponse]
  describe 'pms_poll_inbox_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_receive_deferred_post
  # @param [Hash] opts the optional parameters
  # @option opts [PmsDeferredQueryParameters] :pms_deferred_query_parameters 
  # @return [TransportResponse]
  describe 'pms_receive_deferred_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_registry_search_organization_by_id_post
  # @param [Hash] opts the optional parameters
  # @option opts [OrganizationIdSearchParameters] :organization_id_search_parameters 
  # @return [TransportResponse]
  describe 'pms_registry_search_organization_by_id_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_registry_search_organization_discrete_post
  # @param [Hash] opts the optional parameters
  # @option opts [OrganizationSearchParameters] :organization_search_parameters 
  # @return [TransportResponse]
  describe 'pms_registry_search_organization_discrete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_registry_search_organization_elastic_post
  # @param [Hash] opts the optional parameters
  # @option opts [OrganizationElasticSearchParameters] :organization_elastic_search_parameters 
  # @return [TransportResponse]
  describe 'pms_registry_search_organization_elastic_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_registry_search_practitioner_by_id_post
  # @param [Hash] opts the optional parameters
  # @option opts [PractitionerIdSearchParameters] :practitioner_id_search_parameters 
  # @return [TransportResponse]
  describe 'pms_registry_search_practitioner_by_id_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_registry_search_search_practitioner_discrete_post
  # @param [Hash] opts the optional parameters
  # @option opts [PractitionerSearchParameters] :practitioner_search_parameters 
  # @return [TransportResponse]
  describe 'pms_registry_search_search_practitioner_discrete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_registry_search_search_practitioner_elastic_post
  # @param [Hash] opts the optional parameters
  # @option opts [PractitionerElasticSearchParameters] :practitioner_elastic_search_parameters 
  # @return [TransportResponse]
  describe 'pms_registry_search_search_practitioner_elastic_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_submit_to_inbox_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [TransportResponse]
  describe 'pms_submit_to_inbox_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_from_xml_notification_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [NotificationMessageIssue]
  describe 'pms_transform_from_xml_notification_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_from_xml_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [InboxMessageResponse]
  describe 'pms_transform_from_xml_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_from_xml_search_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [ProviderRegistrySearchResponse]
  describe 'pms_transform_from_xml_search_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_to_xml_acknowledgment_post
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :request_body 
  # @return [String]
  describe 'pms_transform_to_xml_acknowledgment_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_to_xml_clinician_communication_post
  # @param [Hash] opts the optional parameters
  # @option opts [ClinicianCommunication] :clinician_communication 
  # @return [String]
  describe 'pms_transform_to_xml_clinician_communication_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_to_xml_notification_message_post
  # @param [Hash] opts the optional parameters
  # @option opts [NotificationMessage] :notification_message 
  # @return [String]
  describe 'pms_transform_to_xml_notification_message_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_to_xml_pms_adapt_request_post
  # @param [Hash] opts the optional parameters
  # @option opts [PmsAdaptRequest] :pms_adapt_request 
  # @return [String]
  describe 'pms_transform_to_xml_pms_adapt_request_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_to_xml_pms_cancel_response_post
  # @param [Hash] opts the optional parameters
  # @option opts [PmsCancelResponse] :pms_cancel_response 
  # @return [String]
  describe 'pms_transform_to_xml_pms_cancel_response_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_to_xml_pms_dispense_cancel_notification_post
  # @param [Hash] opts the optional parameters
  # @option opts [PmsDispenseCancelNotification] :pms_dispense_cancel_notification 
  # @return [String]
  describe 'pms_transform_to_xml_pms_dispense_cancel_notification_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_to_xml_pms_dispense_notification_post
  # @param [Hash] opts the optional parameters
  # @option opts [PmsDispenseNotification] :pms_dispense_notification 
  # @return [String]
  describe 'pms_transform_to_xml_pms_dispense_notification_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_to_xml_pms_prescribe_request_post
  # @param [Hash] opts the optional parameters
  # @option opts [PmsPrescribeRequest] :pms_prescribe_request 
  # @return [String]
  describe 'pms_transform_to_xml_pms_prescribe_request_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pms_transform_to_xml_pms_renewal_request_post
  # @param [Hash] opts the optional parameters
  # @option opts [PmsRenewalRequest] :pms_renewal_request 
  # @return [String]
  describe 'pms_transform_to_xml_pms_renewal_request_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
