=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PrescribeItClient::AdaptMedicationOrder
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PrescribeItClient::AdaptMedicationOrder do
  let(:instance) { PrescribeItClient::AdaptMedicationOrder.new }

  describe 'test an instance of AdaptMedicationOrder' do
    it 'should create an instance of AdaptMedicationOrder' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PrescribeItClient::AdaptMedicationOrder)
    end
  end

  describe 'test attribute "adapt_reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "original_order_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "stop_notification"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
