=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.3.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::AddressTypeEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::AddressTypeEnum do
  let(:instance) { OpenapiClient::AddressTypeEnum.new }

  describe 'test an instance of AddressTypeEnum' do
    it 'should create an instance of AddressTypeEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::AddressTypeEnum)
    end
  end

end
