=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PrescribeItClient::CancelMedicationOrderReferenceRevoked
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PrescribeItClient::CancelMedicationOrderReferenceRevoked do
  let(:instance) { PrescribeItClient::CancelMedicationOrderReferenceRevoked.new }

  describe 'test an instance of CancelMedicationOrderReferenceRevoked' do
    it 'should create an instance of CancelMedicationOrderReferenceRevoked' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PrescribeItClient::CancelMedicationOrderReferenceRevoked)
    end
  end

  describe 'test attribute "request_cancel_reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cancel_reason_description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_high_priority"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
