=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CommunicationPriorityHolder
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CommunicationPriorityHolder do
  let(:instance) { OpenapiClient::CommunicationPriorityHolder.new }

  describe 'test an instance of CommunicationPriorityHolder' do
    it 'should create an instance of CommunicationPriorityHolder' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CommunicationPriorityHolder)
    end
  end

  describe 'test attribute "exact_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "overridden_binding"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
