=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PrescribeItClient::CommunicationPriorityEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PrescribeItClient::CommunicationPriorityEnum do
  let(:instance) { PrescribeItClient::CommunicationPriorityEnum.new }

  describe 'test an instance of CommunicationPriorityEnum' do
    it 'should create an instance of CommunicationPriorityEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PrescribeItClient::CommunicationPriorityEnum)
    end
  end

end
