=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.3.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::DateWithPrecision
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::DateWithPrecision do
  let(:instance) { OpenapiClient::DateWithPrecision.new }

  describe 'test an instance of DateWithPrecision' do
    it 'should create an instance of DateWithPrecision' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::DateWithPrecision)
    end
  end

  describe 'test attribute "precision"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
