=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.3.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::DateWithPrecisionPrecision
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::DateWithPrecisionPrecision do
  let(:instance) { OpenapiClient::DateWithPrecisionPrecision.new }

  describe 'test an instance of DateWithPrecisionPrecision' do
    it 'should create an instance of DateWithPrecisionPrecision' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::DateWithPrecisionPrecision)
    end
  end

end
