=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.3.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::IssueTypeHolder
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::IssueTypeHolder do
  let(:instance) { OpenapiClient::IssueTypeHolder.new }

  describe 'test an instance of IssueTypeHolder' do
    it 'should create an instance of IssueTypeHolder' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::IssueTypeHolder)
    end
  end

  describe 'test attribute "exact_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "overridden_binding"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
