=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::MedicationDispenseTask
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::MedicationDispenseTask do
  let(:instance) { OpenapiClient::MedicationDispenseTask.new }

  describe 'test an instance of MedicationDispenseTask' do
    it 'should create an instance of MedicationDispenseTask' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::MedicationDispenseTask)
    end
  end

  describe 'test attribute "dispense"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "split_pharmacy_rx_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "split_prescription"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
