=begin
#PrescribeIT SDK REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 5.0.27

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.53
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PrescribeItClient::PharmacyBulkSearchByIdParameters
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PharmacyBulkSearchByIdParameters' do
  before do
    # run before each test
    @instance = PrescribeItClient::PharmacyBulkSearchByIdParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PharmacyBulkSearchByIdParameters' do
    it 'should create an instance of PharmacyBulkSearchByIdParameters' do
      expect(@instance).to be_instance_of(PrescribeItClient::PharmacyBulkSearchByIdParameters)
    end
  end
  describe 'test attribute "registry_identifiers"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "last_updated"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
