=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PrescribeItClient::PharmacyBulkSearchByIdParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PrescribeItClient::PharmacyBulkSearchByIdParameters do
  let(:instance) { PrescribeItClient::PharmacyBulkSearchByIdParameters.new }

  describe 'test an instance of PharmacyBulkSearchByIdParameters' do
    it 'should create an instance of PharmacyBulkSearchByIdParameters' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PrescribeItClient::PharmacyBulkSearchByIdParameters)
    end
  end

  describe 'test attribute "registry_identifiers"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "last_updated"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
