=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PmsRxDispenseMedicationOrderDispenseRequestPmsRx
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PmsRxDispenseMedicationOrderDispenseRequestPmsRx do
  let(:instance) { OpenapiClient::PmsRxDispenseMedicationOrderDispenseRequestPmsRx.new }

  describe 'test an instance of PmsRxDispenseMedicationOrderDispenseRequestPmsRx' do
    it 'should create an instance of PmsRxDispenseMedicationOrderDispenseRequestPmsRx' do
      expect(instance).to be_instance_of(OpenapiClient::PmsRxDispenseMedicationOrderDispenseRequestPmsRx)
    end
  end
  describe 'test attribute "dispense_interval_days"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "quantity"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "expected_supply_duration_days"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
