=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PrescribeItClient::PrescriptionRenewalRejectReasonEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PrescribeItClient::PrescriptionRenewalRejectReasonEnum do
  let(:instance) { PrescribeItClient::PrescriptionRenewalRejectReasonEnum.new }

  describe 'test an instance of PrescriptionRenewalRejectReasonEnum' do
    it 'should create an instance of PrescriptionRenewalRejectReasonEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PrescribeItClient::PrescriptionRenewalRejectReasonEnum)
    end
  end

end
