=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.3.9.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PrescriptionDoseQuantityUnitEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PrescriptionDoseQuantityUnitEnum do
  let(:instance) { OpenapiClient::PrescriptionDoseQuantityUnitEnum.new }

  describe 'test an instance of PrescriptionDoseQuantityUnitEnum' do
    it 'should create an instance of PrescriptionDoseQuantityUnitEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PrescriptionDoseQuantityUnitEnum)
    end
  end

end
