=begin
#PrescribeIT SDK REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 5.0.27

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.53
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PrescribeItClient::RenewResponseMedicationOrderApprovedWithChanges
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RenewResponseMedicationOrderApprovedWithChanges' do
  before do
    # run before each test
    @instance = PrescribeItClient::RenewResponseMedicationOrderApprovedWithChanges.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RenewResponseMedicationOrderApprovedWithChanges' do
    it 'should create an instance of RenewResponseMedicationOrderApprovedWithChanges' do
      expect(@instance).to be_instance_of(PrescribeItClient::RenewResponseMedicationOrderApprovedWithChanges)
    end
  end
  describe 'test attribute "input_change_value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
