=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::RenewResponseMedicationOrderApprovedWithChangesAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::RenewResponseMedicationOrderApprovedWithChangesAllOf do
  let(:instance) { OpenapiClient::RenewResponseMedicationOrderApprovedWithChangesAllOf.new }

  describe 'test an instance of RenewResponseMedicationOrderApprovedWithChangesAllOf' do
    it 'should create an instance of RenewResponseMedicationOrderApprovedWithChangesAllOf' do
      expect(instance).to be_instance_of(OpenapiClient::RenewResponseMedicationOrderApprovedWithChangesAllOf)
    end
  end
  describe 'test attribute "input_change_value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
