=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::RenewResponseMedicationOrderDeniedAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::RenewResponseMedicationOrderDeniedAllOf do
  let(:instance) { OpenapiClient::RenewResponseMedicationOrderDeniedAllOf.new }

  describe 'test an instance of RenewResponseMedicationOrderDeniedAllOf' do
    it 'should create an instance of RenewResponseMedicationOrderDeniedAllOf' do
      expect(instance).to be_instance_of(OpenapiClient::RenewResponseMedicationOrderDeniedAllOf)
    end
  end
  describe 'test attribute "reject_reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reject_reason_description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "new_prescription_identifier"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "non_clinician_practitioner"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "original_prescriber"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
