=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SharedPractitionerIdentifierTypeEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SharedPractitionerIdentifierTypeEnum do
  let(:instance) { OpenapiClient::SharedPractitionerIdentifierTypeEnum.new }

  describe 'test an instance of SharedPractitionerIdentifierTypeEnum' do
    it 'should create an instance of SharedPractitionerIdentifierTypeEnum' do
      expect(instance).to be_instance_of(OpenapiClient::SharedPractitionerIdentifierTypeEnum)
    end
  end
end
