=begin
#PrescribeIT SDK REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 5.0.27

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SharedServiceStatusEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SharedServiceStatusEnum do
  let(:instance) { OpenapiClient::SharedServiceStatusEnum.new }

  describe 'test an instance of SharedServiceStatusEnum' do
    it 'should create an instance of SharedServiceStatusEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SharedServiceStatusEnum)
    end
  end

end
